import shutil
from pathlib import Path
from uuid import uuid4

import pytest

from app.core.config import Settings
from app.core.disclosure_detection_rules import is_explicit_ai_disclosure
from app.models import (
    AIInteractionFlow,
    Article50AnalysisResult,
    Evidence,
    EvidenceType,
    ReadinessStatus,
)
from app.services.article50_service import TransparencyAssessmentValidator
from app.services.workspace_service import WorkspaceService
from app.tools.disclosure_tools import (
    DisclosureInspector,
    clear_scan_interactions,
    register_scan_interactions,
)
from app.tools.repository_tools import RepositoryInspector

FIXTURES = Path(__file__).parent / "fixtures"


def _fixture(tmp_path: Path, name: str):
    settings = Settings(workspace_path=tmp_path)
    workspace = WorkspaceService(settings)
    scan_id = str(uuid4())
    workspace.create_workspace(scan_id)
    shutil.copytree(FIXTURES / name, workspace.get_repository_path(scan_id))
    repository = RepositoryInspector(settings, workspace)
    return scan_id, workspace.get_repository_path(scan_id), DisclosureInspector(
        settings, repository
    )


def _interaction() -> AIInteractionFlow:
    return AIInteractionFlow(
        id="chat-interaction",
        name="Customer Support Chatbot",
        user_facing=True,
        frontend_entrypoint="frontend/src/Chat.tsx",
        api_endpoint="POST /api/chat",
        backend_handler="backend/app/api/chat.py",
        ai_provider="Amazon Bedrock",
        ai_model="global.anthropic.claude-sonnet-4-6",
        flow_summary="Chat.tsx calls the chat API, which invokes Amazon Bedrock.",
        evidence=[
            Evidence(
                file="frontend/src/Chat.tsx",
                line=7,
                snippet='const response = await fetch("/api/chat", {',
                type=EvidenceType.USER_INTERACTION,
            ),
            Evidence(
                file="backend/app/api/chat.py",
                line=7,
                snippet='@router.post("/api/chat")',
                type=EvidenceType.API_ROUTE,
            ),
            Evidence(
                file="backend/app/api/chat.py",
                line=9,
                snippet='return {"reply": generate_reply(payload["message"])}',
                type=EvidenceType.BACKEND_HANDLER,
            ),
            Evidence(
                file="backend/app/services/ai.py",
                line=7,
                snippet="response = bedrock.converse(",
                type=EvidenceType.MODEL_CALL,
            ),
        ],
        confidence=0.93,
    )


@pytest.mark.parametrize(
    "text",
    [
        "You are chatting with an AI assistant.",
        "Responses are generated by AI.",
        "AI-powered assistant",
        "This assistant uses artificial intelligence",
    ],
)
def test_explicit_disclosure_phrases_support_reasonable_variations(text: str) -> None:
    assert is_explicit_ai_disclosure(text) is True


def test_find_disclosure_candidates_returns_rendered_source_evidence(tmp_path: Path) -> None:
    scan_id, _, inspector = _fixture(tmp_path, "ai_chat_app_disclosed")
    interaction = _interaction()
    register_scan_interactions(scan_id, [interaction])
    try:
        candidates = inspector.find_disclosure_candidates(scan_id, interaction.id)
    finally:
        clear_scan_interactions(scan_id)

    assert candidates == [
        {
            "file": "frontend/src/Chat.tsx",
            "relation": "frontend_entrypoint",
            "line": 17,
            "text": "You are chatting with an AI assistant.",
            "snippet": "<p>You are chatting with an AI assistant.</p>",
        }
    ]


def test_readme_comments_variables_backend_logs_and_dependencies_are_not_disclosures(
    tmp_path: Path,
) -> None:
    scan_id, repository_path, inspector = _fixture(tmp_path, "ai_chat_app")
    chat = repository_path / "frontend" / "src" / "Chat.tsx"
    chat.write_text(
        chat.read_text(encoding="utf-8")
        + '\n// AI assistant component\nconst AI_SERVICE = "bedrock";\n',
        encoding="utf-8",
    )
    ai_service = repository_path / "backend" / "app" / "services" / "ai.py"
    ai_service.write_text(
        ai_service.read_text(encoding="utf-8") + '\nlogger.info("AI request received")\n',
        encoding="utf-8",
    )
    interaction = _interaction()
    register_scan_interactions(scan_id, [interaction])
    try:
        assert inspector.find_disclosure_candidates(scan_id, interaction.id) == []
        assert inspector.search_ui_text(scan_id, "AI") == []
    finally:
        clear_scan_interactions(scan_id)


@pytest.mark.parametrize(
    ("fixture_name", "expected"),
    [
        ("ai_chat_app", ReadinessStatus.ACTION_REQUIRED),
        ("ai_chat_app_disclosed", ReadinessStatus.PASS),
    ],
)
def test_readiness_pass_and_action_required(
    tmp_path: Path, fixture_name: str, expected: ReadinessStatus
) -> None:
    scan_id, _, inspector = _fixture(tmp_path, fixture_name)
    interaction = _interaction()
    register_scan_interactions(scan_id, [interaction])
    try:
        result = TransparencyAssessmentValidator(inspector).validate(
            scan_id, [interaction], Article50AnalysisResult()
        )
    finally:
        clear_scan_interactions(scan_id)

    assessment = result.assessments[0]
    assert assessment.status == expected
    assert assessment.disclosure_detected is (expected == ReadinessStatus.PASS)
    assert assessment.inspected_files == ["frontend/src/Chat.tsx"]
    if expected == ReadinessStatus.PASS:
        assert assessment.disclosure_text == "You are chatting with an AI assistant."
        assert any(item.type == EvidenceType.DISCLOSURE for item in assessment.evidence)
    else:
        assert assessment.disclosure_text is None
        assert all(item.type != EvidenceType.DISCLOSURE_ABSENCE for item in assessment.evidence)


def test_ambiguous_assistant_label_requires_review(tmp_path: Path) -> None:
    scan_id, repository_path, inspector = _fixture(tmp_path, "ai_chat_app")
    chat = repository_path / "frontend" / "src" / "Chat.tsx"
    content = chat.read_text(encoding="utf-8").replace(
        '<form onSubmit={sendMessage}>',
        '<form onSubmit={sendMessage}>\n      <span>Smart assistant</span>',
    )
    chat.write_text(content, encoding="utf-8")
    interaction = _interaction()
    register_scan_interactions(scan_id, [interaction])
    try:
        result = TransparencyAssessmentValidator(inspector).validate(
            scan_id, [interaction], Article50AnalysisResult()
        )
    finally:
        clear_scan_interactions(scan_id)

    assert result.assessments[0].status == ReadinessStatus.NEEDS_REVIEW
    assert result.assessments[0].disclosure_detected is None


def test_dynamically_injected_disclosure_text_requires_review(tmp_path: Path) -> None:
    scan_id, repository_path, inspector = _fixture(tmp_path, "ai_chat_app")
    chat = repository_path / "frontend" / "src" / "Chat.tsx"
    content = chat.read_text(encoding="utf-8").replace(
        '<form onSubmit={sendMessage}>',
        '<form onSubmit={sendMessage}>\n      <p>{transparencyNotice}</p>',
    )
    chat.write_text(content, encoding="utf-8")
    interaction = _interaction()
    register_scan_interactions(scan_id, [interaction])
    try:
        result = TransparencyAssessmentValidator(inspector).validate(
            scan_id, [interaction], Article50AnalysisResult()
        )
    finally:
        clear_scan_interactions(scan_id)

    assert result.assessments[0].status == ReadinessStatus.NEEDS_REVIEW
    assert "dynamically" in result.assessments[0].explanation
